version: '2'

services:

  base:
    build: .
    image: ifrcgo/go-api:latest
    ports:
      - 8080:8080
    entrypoint: /bin/bash
    env_file: .env
    volumes:
      - '.:/home/ifrc/work'

  db:
    image: 'mdillon/postgis:9.6'
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres

  test:
    image: ifrcgo/go-api:latest
    working_dir: /home/ifrc/work
    entrypoint: bash -c './manage.py migrate; ./manage.py test'
    env_file: .env
    volumes:
      - '.:/home/ifrc/work'

  manage:
    image: ifrcgo/go-api:latest
    working_dir: /home/ifrc/work
    entrypoint: ./manage.py
    env_file: .env
    volumes:
      - '.:/home/ifrc/work'

  server:
    image: ifrcgo/go-api:latest
    entrypoint: runserver.sh
    env_file: .env
    ports:
      - "8000:80"
